### ISSUE TITLE
typeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by sahadikr1** [repl-it-discord/all-seeing-bot#9]
i got this error message , please help me to fix 
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
 python main.py
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from background_tasks import bg_tasks
  File "/home/runner/all-seeing-bot/background_tasks.py", line 6, in <module>
    from tools.read_write import read, write
  File "/home/runner/all-seeing-bot/tools/read_write.py", line 6, in <module>
    mongo_link = os.getenv('mlab_link') + '?retryWrites=false'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by AllAwesome497** [comment]
That's because you don't have the right .env variables. I haven't documented those yet.
